{   This include file defines the raw keyboard key codes in a Microsoft
*   Windows system.
}
type
  winkey_k_t = (
    winkey_lbutton_k = 16#01,          {Left mouse button}
    winkey_rbutton_k = 16#02,          {Right mouse button}
    winkey_cancel_k = 16#03,           {Control-break processing}
    winkey_mbutton_k = 16#04,          {Middle mouse button (three-button mouse)}
    winkey_back_k = 16#08,             {BACKSPACE key}
    winkey_tab_k = 16#09,              {TAB key}
    winkey_clear_k = 16#0C,            {CLEAR key}
    winkey_return_k = 16#0D,           {ENTER key}
    winkey_shift_k = 16#10,            {SHIFT key}
    winkey_control_k = 16#11,          {CTRL key}
    winkey_menu_k = 16#12,             {ALT key}
    winkey_pause_k = 16#13,            {PAUSE key}
    winkey_capital_k = 16#14,          {CAPS LOCK key}
    winkey_escape_k = 16#1B,           {ESC key}
    winkey_space_k = 16#20,            {SPACEBAR}
    winkey_prior_k = 16#21,            {PAGE UP key}
    winkey_next_k = 16#22,             {PAGE DOWN key}
    winkey_end_k = 16#23,              {END key}
    winkey_home_k = 16#24,             {HOME key}
    winkey_left_k = 16#25,             {LEFT ARROW key}
    winkey_up_k = 16#26,               {UP ARROW key}
    winkey_right_k = 16#27,            {RIGHT ARROW key}
    winkey_down_k = 16#28,             {DOWN ARROW key}
    winkey_select_k = 16#29,           {SELECT key}
    winkey_execute_k = 16#2B,          {EXECUTE key}
    winkey_snapshot_k = 16#2C,         {PRINT SCREEN key for Windows 3.0}
    winkey_insert_k = 16#2D,           {INS key}
    winkey_delete_k = 16#2E,           {DEL key}
    winkey_help_k = 16#2F,             {HELP key}
    winkey_0_k = 16#30,                {0 key}
    winkey_1_k = 16#31,                {1 key}
    winkey_2_k = 16#32,                {2 key}
    winkey_3_k = 16#33,                {3 key}
    winkey_4_k = 16#34,                {4 key}
    winkey_5_k = 16#35,                {5 key}
    winkey_6_k = 16#36,                {6 key}
    winkey_7_k = 16#37,                {7 key}
    winkey_8_k = 16#38,                {8 key}
    winkey_9_k = 16#39,                {9 key}
    winkey_a_k = 16#41,                {A key}
    winkey_b_k = 16#42,                {B key}
    winkey_c_k = 16#43,                {C key}
    winkey_d_k = 16#44,                {D key}
    winkey_e_k = 16#45,                {E key}
    winkey_f_k = 16#46,                {F key}
    winkey_g_k = 16#47,                {G key}
    winkey_h_k = 16#48,                {H key}
    winkey_i_k = 16#49,                {I key}
    winkey_j_k = 16#4A,                {J key}
    winkey_k_k = 16#4B,                {K key}
    winkey_l_k = 16#4C,                {L key}
    winkey_m_k = 16#4D,                {M key}
    winkey_n_k = 16#4E,                {N key}
    winkey_o_k = 16#4F,                {O key}
    winkey_p_k = 16#50,                {P key}
    winkey_q_k = 16#51,                {Q key}
    winkey_r_k = 16#52,                {R key}
    winkey_s_k = 16#53,                {S key}
    winkey_t_k = 16#54,                {T key}
    winkey_u_k = 16#55,                {U key}
    winkey_v_k = 16#56,                {V key}
    winkey_w_k = 16#57,                {W key}
    winkey_x_k = 16#58,                {X key}
    winkey_y_k = 16#59,                {Y key}
    winkey_z_k = 16#5A,                {Z key}
    winkey_numpad0_k = 16#60,          {Numeric keypad 0 key}
    winkey_numpad1_k = 16#61,          {Numeric keypad 1 key}
    winkey_numpad2_k = 16#62,          {Numeric keypad 2 key}
    winkey_numpad3_k = 16#63,          {Numeric keypad 3 key}
    winkey_numpad4_k = 16#64,          {Numeric keypad 4 key}
    winkey_numpad5_k = 16#65,          {Numeric keypad 5 key}
    winkey_numpad6_k = 16#66,          {Numeric keypad 6 key}
    winkey_numpad7_k = 16#67,          {Numeric keypad 7 key}
    winkey_numpad8_k = 16#68,          {Numeric keypad 8 key}
    winkey_numpad9_k = 16#69,          {Numeric keypad 9 key}
    winkey_multiply_k = 16#6A,         {Multiply key}
    winkey_add_k = 16#6B,              {Add key}
    winkey_separator_k = 16#6C,        {Separator key}
    winkey_subtract_k = 16#6D,         {Subtract key}
    winkey_decimal_k = 16#6E,          {Decimal key}
    winkey_divide_k = 16#6F,           {Divide key}
    winkey_f1_k = 16#70,               {F1 key}
    winkey_f2_k = 16#71,               {F2 key}
    winkey_f3_k = 16#72,               {F3 key}
    winkey_f4_k = 16#73,               {F4 key}
    winkey_f5_k = 16#74,               {F5 key}
    winkey_f6_k = 16#75,               {F6 key}
    winkey_f7_k = 16#76,               {F7 key}
    winkey_f8_k = 16#77,               {F8 key}
    winkey_f9_k = 16#78,               {F9 key}
    winkey_f10_k = 16#79,              {F10 key}
    winkey_f11_k = 16#7A,              {F11 key}
    winkey_f12_k = 16#7B,              {F12 key}
    winkey_f13_k = 16#7C,              {F13 key}
    winkey_f14_k = 16#7D,              {F14 key}
    winkey_f15_k = 16#7E,              {F15 key}
    winkey_f16_k = 16#7F,              {F16 key}
    winkey_f17_k = 16#80,              {F17 key}
    winkey_f18_k = 16#81,              {F18 key}
    winkey_f19_k = 16#82,              {F19 key}
    winkey_f20_k = 16#83,              {F20 key}
    winkey_f21_k = 16#84,              {F21 key}
    winkey_f22_k = 16#85,              {F22 key}
    winkey_f23_k = 16#86,              {F23 key}
    winkey_f24_k = 16#87,              {F24 key}
    winkey_numlock_k = 16#90,          {NUM LOCK key}
    winkey_scroll_k = 16#91);          {SCROLL LOCK key}
